- hosts: all
  tasks:
   - copy:
       src: /etc/group
       dest: /tmp/
    
   - file:
      path: /tmp/ansible 
      state: directory

   - apt:
      name: apache2
      state: present

   - service:
       name: apache2
       state: started
