- hosts: all

  vars:
   mydir:
    - /tmp/abcd-1
    - /tmp/abcd-2
    - /tmp/abcd-3
    - /tmp/abcd-4

   myfile:
    - /etc/passwd
    - /etc/group
    - /etc/shadow
    - /etc/gshadow


   
  tasks:
   - copy:
       src: "{{item}}"
       dest: /tmp
     with_items:
       - "{{myfile}}"
    
   - file:
       path: "{{item}}"
       state: directory
     with_items:
       - "{{mydir}}"


   - copy :
        src: /etc/passwd
        dest: "{{item}}"
     with_items:
        - /tmp/abc-1
        - /tmp/abc-2
        - /tmp/abc-3
    
   - copy :
        src: /etc/passwd
        dest: "{{item}}"
     with_items:
        - "{{ mydir }}"
